### ISSUE TITLE
Add a message when number of genes used as input over the limit (500)

### ISSUE THREAD

**Issue by npklein** [molgenis/molgenis-app-genenetwork#17]
When I search genenetork with more than 500 genes nothing happens. Instead, there should be a dialog box or some other message that the limit of number of genes has been reached (or it should be possible to search with more than 500 genes). 

Happens both with pasting genes as well as uploading a file with > 500 genes. I can send an example file if necessary.

**Comment by royoelen** [comment]
should be fixed as of PRs #22 https://github.com/molgenis/molgenis-app-genenetwork/commit/6f5c2f342f027ce360bafda573b76163fa768484 and #26 https://github.com/molgenis/molgenis-app-genenetwork/commit/c68e99ab9ccfd58496c802bf8ba6ed48070f35b7
