### ISSUE TITLE
Show duplicate genes after searching with multiple genes

### ISSUE THREAD

**Issue by harmbrugge** [molgenis/molgenis-app-genenetwork#20]
There is no warning message when searching with multiple genes, but when opening the network page the duplicate genes are filtered out.

**Comment by royoelen** [comment]
should be fixed as of PRs #22 https://github.com/molgenis/molgenis-app-genenetwork/commit/6f5c2f342f027ce360bafda573b76163fa768484 and #26 https://github.com/molgenis/molgenis-app-genenetwork/commit/c68e99ab9ccfd58496c802bf8ba6ed48070f35b7
