### ISSUE TITLE
P-value for pathway analysis on reactome seems incorrect

### ISSUE THREAD

**Issue by royoelen** [molgenis/molgenis-app-genenetwork#23]
Using this request: https://www.genenetwork.nl/network/ENSG00000271251,ENSG00000251997,ENSG00000167004,ENSG00000254917,ENSG00000213946,ENSG00000232895,ENSG00000230843,ENSG00000260201,ENSG00000099290,ENSG00000225105,ENSG00000275342,ENSG00000236305,ENSG00000234071,ENSG00000166598,ENSG00000253270

and selecting pathway analysis on reactome for cluster 2, shows a P-value that should be lower:
![image](https://user-images.githubusercontent.com/51436605/60493460-25dc9880-9cad-11e9-9fee-8fff1f5bba34.png)

**Comment by PatrickDeelen** [comment]
Problem might be due to extermely low p-value of Translation for: https://www.genenetwork.nl/gene/RP11-126L15.4

**Comment by royoelen** [comment]
a number underflow is probably occurring here

**Comment by royoelen** [comment]
should be fixed as of PR #27 2bdfed16781365c7880bffde928c0491b6e24e8d
