### ISSUE TITLE
HPO links are no longer correct

### ISSUE THREAD

**Issue by royoelen** [molgenis/molgenis-app-genenetwork#39]
When using GADO, after clicking 'Gene Prioritisation', you end on the result page like this: https://genenetwork.nl/gado/HP:0000137,HP:0000153,HP:0000172

From here you should be able to click the HPO terms. The links are however no longer correct. A link for example is: http://www.human-phenotype-ontology.org/hpoweb/showterm?id=HP:0000137
When it should probably be: https://hpo.jax.org/app/browse/term/HP:0000137

**Comment by PatrickDeelen** [comment]
Good catch, they indeed changed the urls. I agree with your suggestion how it should be.

**Comment by royoelen** [comment]
Updated by changing the URLs in hpo_predictions_bonSigOnly_termNames_tranposed.txt
This is a database side issue, not a software side issue. Nonetheless has been fixed on the genenetwork webapp
