### ISSUE TITLE
503 error when uploading a textfile through the web interface

### ISSUE THREAD

**Issue by OlivierBakker** [molgenis/molgenis-app-genenetwork#41]
When I try to upload a .txt file (attached) on GeneNetwork.nl, nothing happens. If I then refresh the page I get a 503 error for a while, after about a minute it is back again. Using Firefox 73.0.1 (64-bit) on Ubuntu 18.04 with Ublock origin and HTTPS everywhere, Noscript (turned off). Same for Chromium (no extensions) Version 80.0.3987.87 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit). Pasting these genes manually does work fine.

[t0.t10.genes.txt](https://github.com/molgenis/molgenis-app-genenetwork/files/4337305/t0.t10.genes.txt)

**Comment by royoelen** [comment]
The upload directory was not set correctly on the server for some reason, causing the uploaded files to not be found. Another server side error made it so that this would make the application exit instead of returning this error. This has been resolved.
